// Code generated by "stringer -type=DataType token/data-type.go"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[String-0]
	_ = x[Any-1]
	_ = x[Bool-2]
	_ = x[ComparisonFunction-3]
	_ = x[ContextPath-4]
	_ = x[Float64-5]
	_ = x[Int-6]
	_ = x[JSONPath-7]
	_ = x[Slice-8]
	_ = x[SliceTokenMap-9]
	_ = x[State-10]
	_ = x[StringMap-11]
	_ = x[StringSlice-12]
	_ = x[TimestampType-13]
	_ = x[TokenMap-14]
	_ = x[UInt64-15]
	_ = x[Function-16]
}

const _DataType_name = "StringAnyBoolComparisonFunctionContextPathFloat64IntJSONPathSliceSliceTokenMapStateStringMapStringSliceTimestampTypeTokenMapUInt64Function"

var _DataType_index = [...]uint8{0, 6, 9, 13, 31, 42, 49, 52, 60, 65, 78, 83, 92, 103, 116, 124, 130, 138}

func (i DataType) String() string {
	if i < 0 || i >= DataType(len(_DataType_index)-1) {
		return "DataType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DataType_name[_DataType_index[i]:_DataType_index[i+1]]
}
